/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PRG381_Milestone2.view;

import PRG381_Milestone2.controller.FeedbackController;
import PRG381_Milestone2.model.Feedback;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author User
 */
public class FeedbackPanel extends javax.swing.JPanel {

    private FeedbackController controller;
    
    private List<Feedback> feedbackList = new ArrayList<>();
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form FeedbackPanel
     */ 
    public FeedbackPanel() {
        initComponents();
        controller = new FeedbackController(MainFrame.db.getConnection());
        tableModel = (DefaultTableModel) tblFeedback.getModel();
        
        loadAllFeedback();
        
    }
    
    
    
    public void loadAllFeedback(){
        feedbackList = controller.getAllFeedback();
        tableModel.setRowCount(0);
        
        for (Feedback f : feedbackList){
            tableModel.addRow(new Object[]{
                f.getId(),
                f.getStudent(),
                f.getRating(),
                f.getComments()
            });
        }
    }
    
    public void clearFields(){
        txtStudent.setText("");
        spnRating.setValue(0);
        taComments.setText("");
    }
    
    
    private void fillFieldsFromTable(){
        int row = tblFeedback.getSelectedRow();
        
        if (row >= 0){
            //lblID.setText(tableModel.getValueAt(row, 0).toString());
            txtStudent.setText(tableModel.getValueAt(row, 1).toString());
            spnRating.setValue(tableModel.getValueAt(row, 2));
            taComments.setText(tableModel.getValueAt(row,3).toString());
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeedback = new javax.swing.JTable();
        txtStudent = new javax.swing.JTextField();
        lblStudent = new javax.swing.JLabel();
        spnRating = new javax.swing.JSpinner();
        lblRating = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taComments = new javax.swing.JTextArea();
        btnViewAll = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        tblFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "student", "rating", "comments"
            }
        ));
        tblFeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFeedbackMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFeedback);

        lblStudent.setText("Student Full Name:");
        lblStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        spnRating.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        lblRating.setText("Rating:");

        lblComments.setText("Comments:");

        taComments.setColumns(20);
        taComments.setRows(5);
        jScrollPane2.setViewportView(taComments);

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit Feedback");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStudent)
                    .addComponent(lblRating)
                    .addComponent(lblComments)
                    .addComponent(jScrollPane2)
                    .addComponent(txtStudent)
                    .addComponent(spnRating, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(50, 50, 50)
                        .addComponent(btnDelete))
                    .addComponent(btnViewAll)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnViewAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lblRating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblComments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnSubmit))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String student = txtStudent.getText();
        int rating =(int) spnRating.getValue();
        String comments = taComments.getText();
        
        if (student.isEmpty() || comments.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in all fields");
        } else {
            Feedback f = new Feedback(student, rating, comments);
            
            if (controller.addFeedback(f)){
                JOptionPane.showMessageDialog(this, "Feedback submitted");
                
                clearFields();
                loadAllFeedback();
            }else{
                JOptionPane.showMessageDialog(this, "Feedback failed to submit");
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        loadAllFeedback();
        clearFields();
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblFeedback.getSelectedRow();
        if (row < 0){
            JOptionPane.showMessageDialog(this, "Select a row to update");
            return;
        }
        
        int id = (int) tableModel.getValueAt(row, 0);
        String student = txtStudent.getText();
        int rating =(int) spnRating.getValue();
        String comments = taComments.getText();
        
        Feedback f = new Feedback(id,student,rating,comments);
        
        if (controller.updateFeedback(f)){
            JOptionPane.showMessageDialog(this, "Feedback Updated");
            clearFields();
            loadAllFeedback();
        } else {
            JOptionPane.showMessageDialog(this, "Feedback failed to update");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblFeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFeedbackMouseClicked
        fillFieldsFromTable();
    }//GEN-LAST:event_tblFeedbackMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblFeedback.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a row to delete.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete this feedback?","Confirm Delete",JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION){
            int id = (int) tableModel.getValueAt(row, 0);
            if (controller.deleteFeedback(id)) {
                JOptionPane.showMessageDialog(this, "Feedback removed.");
                clearFields();
                loadAllFeedback();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JSpinner spnRating;
    private javax.swing.JTextArea taComments;
    private javax.swing.JTable tblFeedback;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables
}
