/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRG381_Milestone2.view;

import PRG381_Milestone2.controller.DBConnection;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    public static DBConnection db = new DBConnection();
    private boolean darkMode = true;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        try {
            db.connect();
            db.createTables();   // create tables if not already created
        } catch (ClassNotFoundException e){
            System.out.println("Failed to connect");
            e.printStackTrace();
        }
        
        tabbedPane.removeAll(); // clear dummy tabs

        tabbedPane.addTab("Appointments", new AppointmentPanel());
        tabbedPane.addTab("Counselors", new CounselorPanel());
        tabbedPane.addTab("Feedback", new FeedbackPanel());
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        pnlAppointment = new javax.swing.JPanel();
        pnlCounselor = new javax.swing.JPanel();
        pnlFeedback = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        btnSwitchTheme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wellness Management System");
        setSize(new java.awt.Dimension(900, 600));

        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlAppointmentLayout = new javax.swing.GroupLayout(pnlAppointment);
        pnlAppointment.setLayout(pnlAppointmentLayout);
        pnlAppointmentLayout.setHorizontalGroup(
            pnlAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pnlAppointmentLayout.setVerticalGroup(
            pnlAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Appointment", pnlAppointment);

        javax.swing.GroupLayout pnlCounselorLayout = new javax.swing.GroupLayout(pnlCounselor);
        pnlCounselor.setLayout(pnlCounselorLayout);
        pnlCounselorLayout.setHorizontalGroup(
            pnlCounselorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pnlCounselorLayout.setVerticalGroup(
            pnlCounselorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Counselor", pnlCounselor);

        javax.swing.GroupLayout pnlFeedbackLayout = new javax.swing.GroupLayout(pnlFeedback);
        pnlFeedback.setLayout(pnlFeedbackLayout);
        pnlFeedbackLayout.setHorizontalGroup(
            pnlFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        pnlFeedbackLayout.setVerticalGroup(
            pnlFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Feedback", pnlFeedback);

        tabbedPane.setSelectedComponent(pnlAppointment);

        lblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblDashboard.setText("Wellness Management System Dashboard");

        btnSwitchTheme.setText("Light Mode");
        btnSwitchTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSwitchTheme)
                .addGap(40, 40, 40))
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSwitchTheme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSwitchThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchThemeActionPerformed
        try {
            if (darkMode){
                UIManager.setLookAndFeel(new FlatLightLaf());
                btnSwitchTheme.setText("Dark Mode");
            } else {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                btnSwitchTheme.setText("Light Mode");
            }
            
            SwingUtilities.updateComponentTreeUI(this);
            darkMode = !darkMode;
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSwitchThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSwitchTheme;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JPanel pnlAppointment;
    private javax.swing.JPanel pnlCounselor;
    private javax.swing.JPanel pnlFeedback;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
